site_name: Gnosis Development Kit
repo_url: https://github.com/gnosis/gnosis-management
site_description: Gnosis Development Kit Documentation
theme: readthedocs
extra_css: [extra.css]
pages:
    - Introduction: index.md
    - Core Components:
        - 'GnosisDB': 'core-components/gnosisdb.md'
        - 'GnosisJS': 'core-components/gnosisjs.md'
        - 'Gnosis contracts': 'core-components/gnosis_contracts.md'
        - 'Gnosis management interface': 'core-components/management.md'
